name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository 🛒
        uses: actions/checkout@v5

      - uses: GuillaumeFalourd/setup-rsync@v1.2

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: npm
          cache-dependency-path: "package-lock.json"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies 🔧
        # include devDependencies https://stackoverflow.com/a/64648870
        run: npm ci --audit=false --include=dev --include=optional --include=peer

      - name: Build package 🏗️
        run: npm run build
